source("renv/activate.R")
renv::settings$ignored.packages("redpul", persist = FALSE)
options(box.path = "functions")
options(ndexr_sqlite_path = "redditdb.sqlite")
options(state.verbose = FALSE)
options(quietly = TRUE)
options("shiny.port" = 9000)
options("shiny.host" = "127.0.0.1")
options("ec2.nginx.conf" = "3.137.10.251")
options("localhost" = "192.168.0.68")
options("domain" = "ndexr.com")
options(nflreadr.verbose = FALSE)
box::use(. / functions / aws)
box::use(. / functions / nginx / nginx)
go <- function() {
  rstudioapi::restartSession("box::use(./functions/main);main$main()")
}
