source("renv/activate.R")
renv::settings$ignored.packages("redpul", persist = FALSE)
options(box.path = "functions")
options(ndexr_sqlite_path = "redditdb.sqlite")
options(state.verbose = FALSE)
options(quietly = TRUE)
