version: "2"
services:
  nginx:
    # image: nginx:latest
    container_name: test-nginx
    build: 
      context: .
      dockerfile: Dockerfile.nginx
    ports:
      - '8620:80'
    links:
      # - "appdev"
      - "appprod"
    depends_on:
      # - "appdev"
      - "appprod"
    network_mode: bridge
  # appdev:
  #   image: registry.gitlab.com/fdrennan/bmrn-test:bmrn-test-dev
  #   container_name: test-app
  #   # build: .
  #   restart: always
  #   user: 'root'
  #   command: ["R", "-e", "shiny::runApp('/app/app.R', port = 5000, launch.browser=FALSE, host='0.0.0.0')"]
  #   volumes:
  #     - './test_output:/app/test_output'
  #   network_mode: bridge
  appprod:
    image: registry.gitlab.com/fdrennan/bmrn-test:bmrn-test-prod
    container_name: test-app
    # build: .
    restart: always
    expose: 
      - '5000'
    user: 'root'
    command: ["R", "-e", "shiny::runApp('/app/app.R', port = 5000, launch.browser=FALSE, host='0.0.0.0')"]
    volumes:
      - './test_output:/app/test_output'
    network_mode: bridge
