# https://www.domysee.com/blogposts/reverse-proxy-nginx-docker-compose
version: '3.4'
services:
  nginx:
    image: nginx:latest
    container_name: incoming_http
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - '80:80'
      - '443:443'
    links:
      - app
  app:
    container_name: ndexr_app
    image: registry.gitlab.com/fdrennan/ndexr:latest
    restart: always
    user: 'root'
    expose:
      - '9000'
    command: ["R", "-e", "source('run.r')"]

