version: "2"
services:
  nginx:
    # image: nginx:latest
    container_name: test-nginx
    build: 
      context: .
      dockerfile: Dockerfile.nginx
    ports:
      - '8620:80'
    links:
      - "appdev"
      - "appprod"
    depends_on:
      - "appdev"
      - "appprod"
    network_mode: bridge
  appdev:
    image: git.bmrn.com:4567/qsci/bmrn-test:dev
    container_name: test-app-dev
    # build: .
    restart: always
    ports:
      - '8622:8622'
    expose: 
      - '8622'
    user: 'root'
    command: ["R", "-e", "options(shiny.port=8622);options(shiny.host='0.0.0.0');shiny::runApp('/app/app.R',launch.browser=FALSE)"]
    volumes:
      - './test_output:/app/test_output'
    network_mode: bridge
  appprod:
    image: git.bmrn.com:4567/qsci/bmrn-test:prod
    container_name: test-app
    # build: .
    restart: always
    ports:
      - '8621:8621'
    expose: 
      - '8621'
    user: 'root'
    command: ["R", "-e", "options(shiny.port=8621);options(shiny.host='0.0.0.0');shiny::runApp('/app/app.R',launch.browser=FALSE)"]
    volumes:
      - './test_output:/app/test_output'
    network_mode: bridge
