# https://www.domysee.com/blogposts/reverse-proxy-nginx-docker-compose
version: '3.4'
services:
  app:
    container_name: ndexr_app
    build: .
    command: ["R", "-e", "box::use(./functions/main);main$$main()"]
    restart: always
    user: 'root'
    ports:
      - '3000:9000'
    expose:
      - '9000'
    volumes:
      - './functions:/app/functions'
  selenium:
    container_name: rselenium
    image: selenium/standalone-firefox
    ports:
      - '4445:4444'
