version: "2"
services:
  nginx:
    image: nginx:latest
    container_name: test-nginx
    volumes:
      - './nginx:/etc/nginx'
    ports:
      - '8620:80'
    links:
      - "app"
    depends_on:
      - "app"
    network_mode: bridge
  app:
    image: registry.gitlab.com/fdrennan/bmrn-test:bmrn-test-dev
    container_name: test-app
    # build: .
    restart: always
    user: 'root'
    ports:
    - '5000:5000'
    expose:
    - '5000'
    command: ["R", "-e", "shiny::runApp('/app/app.R', port = 5000, launch.browser=FALSE, host='0.0.0.0')"]
    volumes:
      - './test_output:/app/test_output'
    network_mode: bridge

