# https://www.domysee.com/blogposts/reverse-proxy-nginx-docker-compose
version: '3.4'
services:
  nginx:
    image: nginx:latest
    container_name: incoming_http
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - '9000:80'
    links:
      - app
      - '443:443'
  app:
    container_name: ndexr_app
    build: .
    command: ["R", "-e", "source('run.r')"]
    restart: always
    user: 'root'
    expose:
      - '9000'
    volumes:
      - './functions:/app/functions'
