# https://www.domysee.com/blogposts/reverse-proxy-nginx-docker-compose
version: '3.4'
services:
  app:
    container_name: ndexr_app
    image: registry.gitlab.com/fdrennan/ndexr:shiny
    restart: always
    user: 'root'
    ports:
      - '80:9000'
    expose:
      - '9000'
    command: ["R", "-e", "shiny::runExample(example = '01_hello', port = 9000, host='0.0.0.0')"]

