# https://www.domysee.com/blogposts/reverse-proxy-nginx-docker-compose
version: '3.4'
services:
  app:
    container_name: ndexr_app
    build: .
    # image: registry.gitlab.com/fdrennan/ndexr:latest
    command: ["R", "-e", "box::use(./functions/main);main$$main()"]
    restart: always
    env_file: .Renviron
    user: 'root'
    ports:
      - '3000:9000'
    expose:
      - '9000'
    volumes:
      - './www:/app/www'
      - './functions:/app/functions'
      - './finances:/app/finances'
      - './bills.rda:/app/bills.rda'
  selenium:
    container_name: rselenium
    image: selenium/standalone-firefox
    ports:
      - '4445:4444'
  qsci_nginx:
    image: nginx:latest
    command: [nginx-debug, '-g', 'daemon off;']
    ports:
      - '8610:80'
  qsci_pgadmin:
    container_name: qsci_pgadmin
    image: dpage/pgadmin4:6.14
    links:
      - qsci_nginx
      - qsci_postgres
    depends_on:
      - qsci_postgres
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
    volumes:
       - qsci_pgadmin:/root/.pgadmin
    ports:
      - "8611:80"
    restart: unless-stopped
  qsci_postgres:
    image: postgres:12.3
    container_name: qsci_postgres
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - '8612:5432'
    expose:
      - '8612'
    volumes:
      - qsci_postgres:/var/lib/postgresql/data
    healthcheck:
        test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
        interval: 30s
        timeout: 30s
        retries: 5
volumes:
    qsci_pgadmin:
    qsci_postgres:

  # postgres:
  #   image: postgres:12.3
  #   container_name: "postgres"
  #   restart: always
  #   ports:
  #     - '5432:5432'
  #   expose:
  #     - '5432'
  #   env_file: .Renviron
  #   volumes:
  #     - ndexr_postgres:/var/lib/postgresql/data
  #     - ./volumes/postgres/backups:/data:Z
  #   healthcheck:
  #       test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
  #       interval: 30s
  #       timeout: 30s
  #       retries: 5

# volumes:
#   ndexr_postgres: {}
