# https://www.domysee.com/blogposts/reverse-proxy-nginx-docker-compose
version: '3.4'
services:
  app:
    container_name: ndexr_app
    image: registry.gitlab.com/fdrennan/ndexr:latest
    restart: always
    user: 'root'
    ports:
      - '80:9000'
    expose:
      - '9000'
    command: ["R", "-e", "source('run.r')"]

