# https://www.domysee.com/blogposts/reverse-proxy-nginx-docker-compose
version: '3.4'
services:
  nginx:
    image: nginx:latest
    container_name: incoming_http
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - '8014:80'
      - '443:443'
    links:
      - app
  app:
    container_name: ndexr_app
    build: .
    env_file:
      - .env
    restart: always
    user: 'root'
    ports:
      - '9000:9000'
    expose:
      - '9000'
    command: ["R", "-e", "source('run.r')"]
    volumes:
      - './run.r:/app/run.r'
      - './.Renviron:/app/.Renviron'
      - './functions/:/app/functions'
      - './node_modules:/app/node_modules'
      - './www:/app/www'
