# https://www.domysee.com/blogposts/reverse-proxy-nginx-docker-compose
version: '3.4'
services:
  app:
    container_name: ndexr_app
    build: .
    command: ["R", "-e", "source('run.r')"]
    restart: always
    user: 'root'
    ports:
      - '80:9000'
    expose:
      - '9000'
    volumes:
      - './functions:/app/functions'
